create table if not exists public.users (
  id bigint generated by default as identity primary key,
  first_name varchar(80) not null,
  last_name varchar(80) not null,
  email varchar(150) not null unique,
  password varchar(255) not null,
  is_admin boolean not null default false,
  correo_verificado boolean not null default false,
  email_verification_token char(64) unique,
  email_verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.users
  add column if not exists is_admin boolean not null default false;

alter table public.users
  add column if not exists failed_login_attempts integer not null default 0,
  add column if not exists locked_until timestamptz,
  add column if not exists last_login_at timestamptz,
  add column if not exists session_expires_at timestamptz;

create table if not exists public.remember_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  selector varchar(18) not null unique,
  token_hash char(64) not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists remember_tokens_user_id_index
  on public.remember_tokens(user_id);

create table if not exists public.password_resets (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token_hash char(64) not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists password_resets_user_id_index
  on public.password_resets(user_id);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(150) not null,
  company varchar(100),
  message text not null,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

alter table public.users enable row level security;
alter table public.remember_tokens enable row level security;
alter table public.password_resets enable row level security;
alter table public.contact_messages enable row level security;

-- Ejecuta esto despues de registrarte para convertir tu cuenta en administrador:
-- update public.users set is_admin = true where email = 'tu-correo@gmail.com';
